## Data Encoding
1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

### Nominal/OHE Encoding
One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using one hot encoding as follows:

1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

In [8]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [10]:
encoder = OneHotEncoder()

In [14]:
#Data
df = pd.DataFrame(
            {'color':['red','blue','green','red','blue','green','blue']}
)

In [16]:
df

   color
0    red
1   blue
2  green
3    red
4   blue
5  green
6   blue

In [22]:
encoded = encoder.fit_transform(df).toarray()

In [24]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [30]:
df_encoded = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [34]:
pd.concat([df,df_encoded], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0
5  green         0.0          1.0        0.0
6   blue         1.0          0.0        0.0

In [40]:
encoder.transform([['blue']]).toarray()

C:\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

# Example

In [45]:
import seaborn as sns

In [51]:
df = sns.load_dataset('tips')

In [55]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [63]:
encoded_S = encoder.fit_transform(df[['sex']]).toarray()

In [77]:
df_s =  pd.DataFrame(encoded_S, columns=encoder.get_feature_names_out())
pd.concat([df['sex'],df_s], axis=1)

        sex  sex_Female  sex_Male
0    Female         1.0       0.0
1      Male         0.0       1.0
2      Male         0.0       1.0
3      Male         0.0       1.0
4    Female         1.0       0.0
..      ...         ...       ...
239    Male         0.0       1.0
240  Female         1.0       0.0
241    Male         0.0       1.0
242    Male         0.0       1.0
243  Female         1.0       0.0

[244 rows x 3 columns]

In [83]:
df['time'].unique

<bound method Series.unique of 0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']>

### Conslusion:
One hot encoding increase number of features like if we have 2 catogries two new features will be added to the data set