## Holiday Package Prediciton

### 1) Problem statement.
"Trips & Travel.Com" company wants to enable and establish a viable business model to expand the customer base.
One of the ways to expand the customer base is to introduce a new offering of packages. Currently, there are 5 types of packages the company is offering * Basic, Standard, Deluxe, Super Deluxe, King. Looking at the data of the last year, we observed that 18% of the customers purchased the packages. However, the marketing cost was quite high because customers were contacted at random without looking at the available information.
The company is now planning to launch a new product i.e. Wellness Tourism Package. Wellness Tourism is defined as Travel that allows the traveler to maintain, enhance or kick-start a healthy lifestyle, and support or increase one's sense of well-being.
However, this time company wants to harness the available data of existing and potential customers to make the marketing expenditure more efficient.
### 2) Data Collection.
The Dataset is collected from https://www.kaggle.com/datasets/susant4learning/holiday-package-purchase-prediction
The data consists of 20 column and 4888 rows.

In [3]:
## importing important libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv('Travel.csv')

In [5]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [6]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [7]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [8]:
df['Occupation'].value_counts()

Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64

In [9]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [10]:
df['Gender'] = df['Gender'].replace('Fe Male','Female')

In [11]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [12]:
df['MaritalStatus'] = df['MaritalStatus'].replace('Unmarried','Single')

In [13]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married     2340
Single      1598
Divorced     950
Name: count, dtype: int64

In [14]:
df[df['Age'].isnull()]

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
11,200011,0,NaN,Self Enquiry,1,21.0,Salaried,Female,2,4.0,Deluxe,3.0,Single,1.0,1,3,0,0.0,Manager,NaN
19,200019,0,NaN,Self Enquiry,1,8.0,Salaried,Male,2,3.0,Basic,3.0,Single,6.0,1,4,0,1.0,Executive,NaN
20,200020,0,NaN,Company Invited,1,17.0,Salaried,Female,3,2.0,Deluxe,3.0,Married,1.0,0,3,1,2.0,Manager,NaN
21,200021,1,NaN,Self Enquiry,3,15.0,Salaried,Male,2,4.0,Deluxe,5.0,Single,1.0,0,2,0,0.0,Manager,18407.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2410,202410,1,NaN,Self Enquiry,1,30.0,Small Business,Male,2,3.0,Basic,4.0,Married,2.0,1,1,0,0.0,Executive,NaN
2413,202413,1,NaN,Self Enquiry,3,21.0,Small Business,Male,2,5.0,Deluxe,3.0,Married,7.0,1,1,0,1.0,Manager,18423.0
2427,202427,1,NaN,Self Enquiry,3,22.0,Small Business,Male,3,3.0,Standard,3.0,Married,3.0,0,5,0,1.0,Senior Manager,18544.0
2430,202430,1,NaN,Self Enquiry,1,14.0,Small Business,Female,3,3.0,Basic,5.0,Married,2.0,1,3,0,2.0,Executive,NaN
2435,202435,1,NaN,Self Enquiry,2,26.0,Small Business,Female,3,3.0,Basic,4.0,Married,1.0,1,3,0,1.0,Executive,18669.0

In [15]:
## Check Misssing Values
##these are the features with nan value

features_with_na = [features for features in df.columns if df[features].isnull().sum()>=1]
for feature in features_with_na:
    print(feature, np.round(df[feature].isnull().mean()*100,3), '% missing values')

Age 4.624 % missing values
TypeofContact 0.511 % missing values
DurationOfPitch 5.135 % missing values
NumberOfFollowups 0.921 % missing values
PreferredPropertyStar 0.532 % missing values
NumberOfTrips 2.864 % missing values
NumberOfChildrenVisiting 1.35 % missing values
MonthlyIncome 4.767 % missing values

In [18]:
df[features_with_na].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

## Imputing Null values
1. Impute Median value for Age column
2. Impute Mode for Type of Contract
3. Impute Median for Duration of Pitch
4. Impute Mode for NumberofFollowup as it is Discrete feature
5. Impute Mode for PreferredPropertyStar
6. Impute Median for NumberofTrips
7. Impute Mode for NumberOfChildrenVisiting
8. Impute Median for MonthlyIncome

In [32]:
#Imputing Median value for Age column
df['Age'].fillna(df['Age'].median(),inplace=True)

#Imputing Mode for Type of Contract
df['TypeofContact'].fillna(df['TypeofContact'].mode()[0],inplace=True)

#Imputing Median for Duration of Pitch
df['DurationOfPitch'].fillna(df['DurationOfPitch'].median(),inplace=True)

#Imputing Mode for NumberofFollowup as it is Discrete feature
df['NumberOfFollowups'].fillna(df['NumberOfFollowups'].mode()[0],inplace=True)

#Imputing Mode for PreferredPropertyStar
df['PreferredPropertyStar'].fillna(df['PreferredPropertyStar'].mode()[0],inplace=True)

#Imputing Median for NumberofTrips
df['NumberOfTrips'].fillna(df['NumberOfTrips'].median(),inplace=True)

#Imputing Mode for NumberOfChildrenVisiting
df['NumberOfChildrenVisiting'].fillna(df['NumberOfChildrenVisiting'].mode()[0],inplace=True)

#Imputing Median for MonthlyIncome
df['MonthlyIncome'].fillna(df['MonthlyIncome'].median(),inplace=True)

In [33]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [34]:
df.drop('CustomerID',axis=1,inplace=True)

### Feature Engineering

In [37]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [40]:
df['Total Visiting'] = df['NumberOfPersonVisiting']+df['NumberOfChildrenVisiting']

In [42]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome,Total Visiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0,2.0

In [45]:
df.drop(columns=['NumberOfPersonVisiting','NumberOfChildrenVisiting'], axis=1,inplace=True)

In [47]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,Total Visiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Single,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Single,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [49]:
#get all numeric features
num_feat = [features for features in df.columns if df[features].dtype!='O']
print('No of Numerical Features: ',len(num_feat))

No of Numerical Features:  12

In [51]:
#get all categorical features
cat_feat = [features for features in df.columns if df[features].dtype=='O']
print('No of Categorical Features: ',len(cat_feat))

No of Categorical Features:  6

In [53]:
#get all discreate features
dis_feat = [features for features in df[num_feat] if len(df[features].unique())<=25]
print('No of Numerical Features: ',len(dis_feat))

No of Numerical Features:  9

In [55]:
#get all continous features
con_feat = [features for features in df[num_feat] if features not in dis_feat]
print('No of Numerical Features: ',len(con_feat))

No of Numerical Features:  3

### Train Test Split

In [58]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,Total Visiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Single,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Single,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [60]:
X = df.drop('ProdTaken' ,axis=1)
Y = df['ProdTaken']

In [62]:
X

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,Total Visiting
0,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Single,1.0,1,2,1,Manager,20993.0,3.0
1,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Single,7.0,1,3,0,Executive,17090.0,3.0
3,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,49.0,Self Enquiry,3,9.0,Small Business,Male,5.0,Deluxe,4.0,Single,2.0,1,1,1,Manager,26576.0,4.0
4884,28.0,Company Invited,1,31.0,Salaried,Male,5.0,Basic,3.0,Single,3.0,1,3,1,Executive,21212.0,6.0
4885,52.0,Self Enquiry,3,17.0,Salaried,Female,4.0,Standard,4.0,Married,7.0,0,1,1,Senior Manager,31820.0,7.0
4886,19.0,Self Enquiry,3,16.0,Small Business,Male,4.0,Basic,3.0,Single,3.0,0,5,0,Executive,20289.0,5.0
4887,36.0,Self Enquiry,1,14.0,Salaried,Male,4.0,Basic,4.0,Single,3.0,1,3,1,Executive,24041.0,6.0

In [64]:
Y

0       1
1       0
2       1
3       0
4       0
       ..
4883    1
4884    1
4885    1
4886    1
4887    1
Name: ProdTaken, Length: 4888, dtype: int64

In [66]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=42)

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ProdTaken               4888 non-null   int64
 1   Age                     4888 non-null   float64
 2   TypeofContact           4888 non-null   object
 3   CityTier                4888 non-null   int64
 4   DurationOfPitch         4888 non-null   float64
 5   Occupation              4888 non-null   object
 6   Gender                  4888 non-null   object
 7   NumberOfFollowups       4888 non-null   float64
 8   ProductPitched          4888 non-null   object
 9   PreferredPropertyStar   4888 non-null   float64
 10  MaritalStatus           4888 non-null   object
 11  NumberOfTrips           4888 non-null   float64
 12  Passport                4888 non-null   int64
 13  PitchSatisfactionScore  4888 non-null   int64
 14  OwnCar                  4888 non-null   int64
 15  Designation             4888 non-null   object
 16  MonthlyIncome           4888 non-null   float64
 17  Total Visiting          4888 non-null   float64
dtypes: float64(7), int64(5), object(6)
memory usage: 687.5+ KB

In [69]:
cat_feat = X.select_dtypes(include='object').columns
num_feat = X.select_dtypes(exclude='object').columns

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

onehot = OneHotEncoder(drop='first')
scaler = StandardScaler()

preprocessor = ColumnTransformer([

            ('OneHotEncoder' , onehot ,cat_feat),
            ('StandardScaler' , scaler , num_feat)
])

In [72]:
preprocessor

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'Total Visiting'],
      dtype='object'))])

In [74]:
X_train = preprocessor.fit_transform(X_train)

In [76]:
X_test = preprocessor.transform(X_test)

In [78]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\anaconda3\lib\site-packages (3.0.0)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from xgboost) (1.13.1)

## Xgboost and other Classifier Training

In [80]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report,ConfusionMatrixDisplay, \
                            precision_score, recall_score, f1_score, roc_auc_score,roc_curve

In [82]:
models = {
        "Random Forest":RandomForestClassifier(),   
        "GradientBoostingClassifier":GradientBoostingClassifier(),
        "DecisionTreeClassifier":DecisionTreeClassifier(),
        "LogisticRegression": LogisticRegression(),
        "XGBoost": XGBClassifier(),
        "AdaBoostClassifier": AdaBoostClassifier()
}

for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    y_pred_train = model.predict(X_train) #traning prediction
    y_pred_test = model.predict(X_test) #test data prediction

    #traning performance metrics
    acc_score_train = accuracy_score(y_pred_train,y_train)
    prec_score_train = precision_score(y_pred_train,y_train)
    f_score_train = f1_score(y_pred_train,y_train)
    recl_score_train = recall_score(y_pred_train,y_train)
    roc_score_train = roc_auc_score(y_pred_train,y_train)

    #test performance metrics
    acc_score_test = accuracy_score(y_pred_test,y_test)
    prec_score_test = precision_score(y_pred_test,y_test)
    f_score_test = f1_score(y_pred_test,y_test)
    recl_score_test = recall_score(y_pred_test,y_test)
    roc_score_test = roc_auc_score(y_pred_test,y_test)

   
    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Accuracy: {:.4f}".format(acc_score_train))
    print('- F1 score: {:.4f}'.format(f_score_train))
    
    print('- Precision: {:.4f}'.format(prec_score_train))
    print('- Recall: {:.4f}'.format(recl_score_train))
    print('- Roc Auc Score: {:.4f}'.format(roc_score_train))

    
    
    print('----------------------------------')
    
    print('Model performance for Test set')
    print('- Accuracy: {:.4f}'.format(acc_score_test))
    print('- F1 score: {:.4f}'.format(f_score_test))
    print('- Precision: {:.4f}'.format(prec_score_test))
    print('- Recall: {:.4f}'.format(recl_score_test))
    print('- Roc Auc Score: {:.4f}'.format(roc_score_test))

    print('='*35)
    print('\n')

Random Forest
Model performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9280
- F1 score: 0.7622
- Precision: 0.6323
- Recall: 0.9592
- Roc Auc Score: 0.9415
===================================


GradientBoostingClassifier
Model performance for Training set
- Accuracy: 0.8895
- F1 score: 0.6281
- Precision: 0.4907
- Recall: 0.8724
- Roc Auc Score: 0.8820
----------------------------------
Model performance for Test set
- Accuracy: 0.8723
- F1 score: 0.5412
- Precision: 0.4126
- Recall: 0.7863
- Roc Auc Score: 0.8339
===================================


DecisionTreeClassifier
Model performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9010
- F1 score: 0.7352
- Precision: 0.7534
- Recall: 0.7179
- Roc Auc Score: 0.8311
===================================


LogisticRegression
Model performance for Training set
- Accuracy: 0.8432
- F1 score: 0.4209
- Precision: 0.2999
- Recall: 0.7061
- Roc Auc Score: 0.7806
----------------------------------
Model performance for Test set
- Accuracy: 0.8445
- F1 score: 0.4207
- Precision: 0.3094
- Recall: 0.6571
- Roc Auc Score: 0.7596
===================================


XGBoost
Model performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9345
- F1 score: 0.7970
- Precision: 0.7040
- Recall: 0.9181
- Roc Auc Score: 0.9277
===================================


AdaBoostClassifier
Model performance for Training set
- Accuracy: 0.8524
- F1 score: 0.4793
- Precision: 0.3572
- Recall: 0.7281
- Roc Auc Score: 0.7966
----------------------------------
Model performance for Test set
- Accuracy: 0.8494
- F1 score: 0.4524
- Precision: 0.3408
- Recall: 0.6726
- Roc Auc Score: 0.7700
===================================

In [84]:
## Hyperparameter Training
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}

xgboost_params = { 
                    'learning_rate':[0.1,0.3,0.5,0.7,0.8],
                    "n_estimators":[40,50,60,70,80],
                    'max_leaves':[0,1,3,5,8],
                    'max_depth':[1,2,3,4 ]                   
}

In [86]:
random_cv_models = [
             ('RF',RandomForestClassifier() , rf_params),
             ('XGBoost',XGBClassifier(),xgboost_params)
]

In [88]:
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name,model,param in random_cv_models:
    rand_cv = RandomizedSearchCV(estimator=model,param_distributions=param,n_iter=100,cv=3,verbose=0,n_jobs=-1)
    rand_cv.fit(X_train,y_train)
    model_param[name] = rand_cv.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

---------------- Best Params for RF -------------------
{'n_estimators': 1000, 'min_samples_split': 2, 'max_features': 8, 'max_depth': None}
---------------- Best Params for XGBoost -------------------
{'n_estimators': 60, 'max_leaves': 0, 'max_depth': 4, 'learning_rate': 0.7}

In [94]:
models = {
        "Random Forest":RandomForestClassifier(n_estimators=1000, min_samples_split=2, max_features=8, max_depth=None), 
        "XGBoost": XGBClassifier(n_estimators=60, max_leaves= 0, max_depth= 4, learning_rate= 0.7 )
}

for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    y_pred_train = model.predict(X_train) #traning prediction
    y_pred_test = model.predict(X_test) #test data prediction

    #traning performance metrics
    acc_score_train = accuracy_score(y_pred_train,y_train)
    prec_score_train = precision_score(y_pred_train,y_train)
    f_score_train = f1_score(y_pred_train,y_train)
    recl_score_train = recall_score(y_pred_train,y_train)
    roc_score_train = roc_auc_score(y_pred_train,y_train)

    #test performance metrics
    acc_score_test = accuracy_score(y_pred_test,y_test)
    prec_score_test = precision_score(y_pred_test,y_test)
    f_score_test = f1_score(y_pred_test,y_test)
    recl_score_test = recall_score(y_pred_test,y_test)
    roc_score_test = roc_auc_score(y_pred_test,y_test)

   
    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Accuracy: {:.4f}".format(acc_score_train))
    print('- F1 score: {:.4f}'.format(f_score_train))
    
    print('- Precision: {:.4f}'.format(prec_score_train))
    print('- Recall: {:.4f}'.format(recl_score_train))
    print('- Roc Auc Score: {:.4f}'.format(roc_score_train))

    
    
    print('----------------------------------')
    
    print('Model performance for Test set')
    print('- Accuracy: {:.4f}'.format(acc_score_test))
    print('- F1 score: {:.4f}'.format(f_score_test))
    print('- Precision: {:.4f}'.format(prec_score_test))
    print('- Recall: {:.4f}'.format(recl_score_test))
    print('- Roc Auc Score: {:.4f}'.format(roc_score_test))

    print('='*35)
    print('\n')

Random Forest
Model performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9345
- F1 score: 0.7917
- Precision: 0.6816
- Recall: 0.9441
- Roc Auc Score: 0.9386
===================================


XGBoost
Model performance for Training set
- Accuracy: 0.9847
- F1 score: 0.9586
- Precision: 0.9297
- Recall: 0.9893
- Roc Auc Score: 0.9865
----------------------------------
Model performance for Test set
- Accuracy: 0.9100
- F1 score: 0.7277
- Precision: 0.6592
- Recall: 0.8122
- Roc Auc Score: 0.8696
===================================